global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: INFO

# Define providers
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: true

# Define entrypoints
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
          permanent: true
  https:
    address: ":443"

# Configure the API
api:
  insecure: true
  dashboard: true

# Define TLS
tls:
  certificates:
    - certFile: "/etc/traefik/certificates/cert.pem"
      keyFile: "/etc/traefik/certificates/key.pem"
